title: Quirkbot CODE
description: Program your Quirkbot with an easy to use, visual interface!
baseurl: "/"

collections:
  - node_categories
  - nodes

# Defaults
permalink:  pretty
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "en"
    values:
      lang: "en"
  -
    scope:
      path: "cn"
    values:
      lang: "cn"
  -
    scope:
      path: "tutorials"
    values:
      layout: "tutorial_single"
      title_format: "{{title}} - Tutorial"
  -
    scope:
      path: "documentation"
    values:
      title_format: "{{title}} - Documentation"
  -
    scope:
      path: "documentation/nodes"
    values:
      layout: "node_documentation_single"
