
title: Quirkbot CODE
description: Program your Quirkbot with an easy to use, visual interface!
baseurl: "/"

collections:
  - node-categories
  - nodes
  
# Defaults
permalink:  pretty
defaults:
  -
    scope:
      path: ""
    values:
      lang: "en"
  -
    scope:
      path: "instructions/nodes"
    values:
      type: "node-documentation"
      layout: "node-documentation"
  -
    scope:
      path: "sv"
    values:
      lang: "sv"
  -
    scope:
      path: "sv/instructions/nodes"
    values:
      layout: "node-doc"

# Build settings
markdown: kramdown
include:
  - _static
