title: Quirkbot CODE
description: Program your Quirkbot with an easy to use, visual interface!
baseurl: "/"
urls:
    production:
        root: Elite
        compiler: https://quirkbot-compiler.herokuapp.com/
        api: http://api-production-1079277390.us-east-1.elb.amazonaws.com/
    stage:
        root: Elite
        compiler: https://quirkbot-compiler-stage.herokuapp.com/
        api: http://ec2contai-ecselast-1aa8efo9kdp65-1013516278.us-east-1.elb.amazonaws.com/
    development:
        root: http://ide-local.quirkbot.com:4000/
        compiler: http://localhost:8080/
        api: http://localhost:3001/
# Build settings
markdown: kramdown
include:
  - _static
