title: Quirkbot CODE
description: Program your Quirkbot with an easy to use, visual interface!
baseurl: "/"

collections:
  - node_categories
  - nodes

# Defaults
permalink:  pretty
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      lang: "en"
  -
    scope:
      path: "help"
    values:
      layout: "help"
  -
    scope:
      path: "help/docs"
    values:
      title_format: "{{title}} - Documentation"
  -
    scope:
      path: "help/docs/nodes"
    values:
      layout: "node_documentation"
