
title: Quirkbot CODE
description: Program your Quirkbot with an easy to use, visual interface!
baseurl: "/"

collections:
  - node_categories
  - nodes

# Defaults
permalink:  pretty
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      lang: "en"
  -
    scope:
      path: "instructions/nodes"
    values:
      layout: "node-documentation"
      title_format: "{{title}} - Documentation"
  -
    scope:
      path: "sv"
    values:
      lang: "sv"
  -
    scope:
      path: "sv/instructions/nodes"
    values:
      layout: "node-documentation"
      title_format: "{{title}} - Documentation"

# Build settings
markdown: kramdown
include:
  - _static
